#!/bin/bash

set -x
set -e

FILES=(
    "../cores/ricoh_2A03/alu/alu.vhdl"
    "../cores/ricoh_2A03/alu/adder_hold_register.vhdl"
    "../cores/ricoh_2A03/alu/a_input_register.vhdl"
    "../cores/ricoh_2A03/alu/b_input_register.vhdl"
    "../cores/ricoh_2A03/alu/core.vhdl"
    "../cores/ricoh_2A03/datapath/index_register.vhdl"
    "../cores/ricoh_2A03/datapath/accumulator.vhdl"
    "../cores/ricoh_2A03/datapath/data_input_latch.vhdl"
    "../cores/ricoh_2A03/datapath/data_output_latch.vhdl"
    "../cores/ricoh_2A03/datapath/status_register.vhdl"
    "../cores/ricoh_2A03/datapath/stack_pointer.vhdl"
    "../cores/ricoh_2A03/datapath/precharge_mosfets.vhdl"
    "../cores/ricoh_2A03/datapath/core.vhdl"
    "../cores/ricoh_2A03/datapath/adh_open_drain_mosfet.vhdl"
    "../cores/ricoh_2A03/datapath/adl_open_drain_mosfet.vhdl"
    "../cores/ricoh_2A03/datapath/pass_mosfet.vhdl"
    "../cores/ricoh_2A03/core.vhdl"
)

pushd $1
eval "$GHDL -i ${FILES[@]}"
popd
