#!/bin/bash

set -x
set -e

pushd $1

# ALU tests
python -m util.run_cocotb mos_6502_alu cores.ricoh_2A03.alu.verify_alu ./cores/ricoh_2A03/alu/alu.vhdl
python -m util.run_cocotb adder_hold_register cores.ricoh_2A03.alu.verify_add ./cores/ricoh_2A03/alu/adder_hold_register.vhdl
python -m util.run_cocotb a_input_register cores.ricoh_2A03.alu.verify_a_input_register ./cores/ricoh_2A03/alu/a_input_register.vhdl
python -m util.run_cocotb b_input_register cores.ricoh_2A03.alu.verify_b_input_register ./cores/ricoh_2A03/alu/b_input_register.vhdl

# Datapath tests
python -m util.run_cocotb index_register cores.ricoh_2A03.datapath.verify_index_register ./cores/ricoh_2A03/datapath/index_register.vhdl
python -m util.run_cocotb accumulator cores.ricoh_2A03.datapath.verify_accumulator ./cores/ricoh_2A03/datapath/accumulator.vhdl
python -m util.run_cocotb data_input_latch cores.ricoh_2A03.datapath.verify_data_input_latch ./cores/ricoh_2A03/datapath/data_input_latch.vhdl
python -m util.run_cocotb data_output_latch cores.ricoh_2A03.datapath.verify_data_output_latch ./cores/ricoh_2A03/datapath/data_output_latch.vhdl
python -m util.run_cocotb status_register cores.ricoh_2A03.datapath.verify_status_register ./cores/ricoh_2A03/datapath/status_register.vhdl
popd
